"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Loader2, RefreshCw, Trash2, Plus } from "lucide-react"
import type { VocabCategory } from "@/lib/vocab-tree"

interface ParentConfigProps {
  tree: VocabCategory[]
  onSave: (tree: VocabCategory[]) => void
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function ParentConfig({ tree, onSave, open, onOpenChange }: ParentConfigProps) {
  const [generatingId, setGeneratingId] = useState<string | null>(null)
  const [newName, setNewName] = useState("")
  const [newEmoji, setNewEmoji] = useState("")
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [error, setError] = useState("")

  const callGenerateApi = async (
    name: string,
    emoji: string,
  ): Promise<{ word: string; emoji: string; children: VocabCategory["children"] } | null> => {
    try {
      const res = await fetch("/api/aac/generate-tree", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ categoryName: name, categoryEmoji: emoji }),
      })
      if (!res.ok) throw new Error("API error")
      return res.json()
    } catch {
      return null
    }
  }

  const handleAdd = async () => {
    const name = newName.trim()
    if (!name) return
    setError("")

    const id = `${name.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}`
    const emoji = newEmoji.trim() || "📋"

    // Optimistic placeholder
    const placeholder: VocabCategory = { id, word: name, emoji, children: [] }
    onSave([...tree, placeholder])
    setNewName("")
    setNewEmoji("")
    setGeneratingId(id)

    const generated = await callGenerateApi(name, emoji)
    if (generated) {
      onSave(
        [...tree, placeholder].map((c) =>
          c.id === id ? { id, word: name, emoji, children: generated.children } : c,
        ),
      )
    } else {
      // Remove placeholder on failure
      onSave(tree.filter((c) => c.id !== id))
      setError(`Could not generate vocabulary for "${name}". Please try again.`)
    }
    setGeneratingId(null)
  }

  const handleRegenerate = async (category: VocabCategory) => {
    setError("")
    setGeneratingId(category.id)
    const generated = await callGenerateApi(category.word, category.emoji)
    if (generated) {
      onSave(
        tree.map((c) =>
          c.id === category.id ? { ...c, children: generated.children } : c,
        ),
      )
    } else {
      setError(`Could not regenerate vocabulary for "${category.word}". Please try again.`)
    }
    setGeneratingId(null)
  }

  const handleDelete = (id: string) => {
    onSave(tree.filter((c) => c.id !== id))
    setDeletingId(null)
  }

  const isBusy = generatingId !== null

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[560px] max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Manage Categories</DialogTitle>
          <DialogDescription>
            Add or remove Level 1 categories. All vocabulary below Level 1 is auto-generated by AI.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {/* Category list */}
          {tree.length === 0 && (
            <p className="text-sm text-muted-foreground text-center py-4">
              No categories yet. Add one below.
            </p>
          )}

          <div className="space-y-2">
            {tree.map((category) => {
              const isGenerating = generatingId === category.id
              const isDeleting = deletingId === category.id
              const hasContent = category.children.length > 0
              const leafCount = category.children.reduce((n, b) => n + b.children.length, 0)

              return (
                <div
                  key={category.id}
                  className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg border"
                >
                  <span className="text-2xl w-9 text-center shrink-0">{category.emoji}</span>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium truncate">{category.word}</p>
                    <p className="text-xs text-gray-500">
                      {isGenerating
                        ? "Generating vocabulary…"
                        : hasContent
                          ? `${category.children.length} sub-categories · ${leafCount} phrases`
                          : "No vocabulary yet — regenerate to create"}
                    </p>
                  </div>

                  <div className="flex items-center gap-2 shrink-0">
                    {isDeleting ? (
                      <>
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => handleDelete(category.id)}
                        >
                          Delete
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setDeletingId(null)}
                        >
                          Cancel
                        </Button>
                      </>
                    ) : (
                      <>
                        <Button
                          variant="outline"
                          size="sm"
                          title="Regenerate vocabulary"
                          onClick={() => handleRegenerate(category)}
                          disabled={isBusy}
                        >
                          {isGenerating ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <RefreshCw className="w-4 h-4" />
                          )}
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          title="Delete category"
                          onClick={() => setDeletingId(category.id)}
                          disabled={isBusy}
                        >
                          <Trash2 className="w-4 h-4 text-red-500" />
                        </Button>
                      </>
                    )}
                  </div>
                </div>
              )
            })}
          </div>

          {/* Error */}
          {error && (
            <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
              {error}
            </p>
          )}

          {/* Add new category */}
          <div className="border-t pt-4 space-y-3">
            <p className="text-sm font-medium">Add New Category</p>
            <div className="flex gap-2">
              <input
                type="text"
                value={newEmoji}
                onChange={(e) => setNewEmoji(e.target.value)}
                placeholder="🎯"
                className="w-14 text-center text-xl border rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-primary"
                maxLength={8}
                aria-label="Category emoji"
              />
              <input
                type="text"
                value={newName}
                onChange={(e) => setNewName(e.target.value)}
                placeholder="Category name (e.g., Sports)"
                className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                onKeyDown={(e) => e.key === "Enter" && !isBusy && handleAdd()}
                aria-label="Category name"
              />
              <Button
                onClick={handleAdd}
                disabled={!newName.trim() || isBusy}
                className="shrink-0"
              >
                {isBusy && generatingId !== null && generatingId.startsWith(newName.toLowerCase()) ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <>
                    <Plus className="w-4 h-4 mr-1" />
                    Add
                  </>
                )}
              </Button>
            </div>
            <p className="text-xs text-gray-500">
              Adding a category automatically generates all sub-categories and phrases. This takes a few seconds.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
