"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Loader2, RefreshCw, Trash2, Plus, ArrowLeft, Pencil } from "lucide-react"
import type { VocabCategory } from "@/lib/vocab-tree"

interface ParentConfigProps {
  tree: VocabCategory[]
  onSave: (tree: VocabCategory[]) => void
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function ParentConfig({ tree, onSave, open, onOpenChange }: ParentConfigProps) {
  const [generatingId, setGeneratingId] = useState<string | null>(null)
  const [newName, setNewName] = useState("")
  const [newEmoji, setNewEmoji] = useState("")
  const [newDescription, setNewDescription] = useState("")
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editName, setEditName] = useState("")
  const [editEmoji, setEditEmoji] = useState("")
  const [editDescription, setEditDescription] = useState("")
  const [error, setError] = useState("")

  if (!open) return null

  const startEdit = (category: VocabCategory) => {
    setEditingId(category.id)
    setEditName(category.word)
    setEditEmoji(category.emoji)
    setEditDescription(category.description ?? "")
  }

  const cancelEdit = () => {
    setEditingId(null)
    setEditName("")
    setEditEmoji("")
    setEditDescription("")
  }

  const handleSaveEdit = (category: VocabCategory) => {
    const name = editName.trim()
    if (!name) return
    const emoji = editEmoji.trim() || category.emoji
    const description = editDescription.trim() || undefined
    onSave(tree.map((c) => (c.id === category.id ? { ...c, word: name, emoji, description } : c)))
    cancelEdit()
  }

  const callGenerateApi = async (
    name: string,
    emoji: string,
    description?: string,
  ): Promise<{ word: string; emoji: string; children: VocabCategory["children"] } | null> => {
    try {
      const res = await fetch("/api/aac/generate-tree", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ categoryName: name, categoryEmoji: emoji, categoryDescription: description }),
      })
      if (!res.ok) throw new Error("API error")
      return res.json()
    } catch {
      return null
    }
  }

  const handleAdd = async () => {
    const name = newName.trim()
    if (!name) return
    setError("")

    const id = `${name.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}`
    const emoji = newEmoji.trim() || "📋"
    const description = newDescription.trim() || undefined

    const placeholder: VocabCategory = { id, word: name, emoji, description, children: [] }
    onSave([...tree, placeholder])
    setNewName("")
    setNewEmoji("")
    setNewDescription("")
    setGeneratingId(id)

    const generated = await callGenerateApi(name, emoji, description)
    if (generated) {
      onSave(
        [...tree, placeholder].map((c) =>
          c.id === id ? { id, word: name, emoji, description, children: generated.children } : c,
        ),
      )
    } else {
      onSave(tree.filter((c) => c.id !== id))
      setError(`Could not generate vocabulary for "${name}". Please try again.`)
    }
    setGeneratingId(null)
  }

  const handleRegenerate = async (category: VocabCategory) => {
    setError("")
    setGeneratingId(category.id)
    const generated = await callGenerateApi(category.word, category.emoji, category.description)
    if (generated) {
      onSave(
        tree.map((c) =>
          c.id === category.id ? { ...c, children: generated.children } : c,
        ),
      )
    } else {
      setError(`Could not regenerate vocabulary for "${category.word}". Please try again.`)
    }
    setGeneratingId(null)
  }

  const handleDelete = (id: string) => {
    onSave(tree.filter((c) => c.id !== id))
    setDeletingId(null)
  }

  const isBusy = generatingId !== null

  return (
    <div className="fixed inset-0 z-50 bg-gradient-to-br from-blue-50 to-purple-50 overflow-y-auto">
      <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
        {/* Header */}
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => onOpenChange(false)}
            className="flex items-center gap-2 bg-white"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-800">Manage Categories</h1>
            <p className="text-sm text-gray-500 mt-0.5">
              Add, edit, or remove Level 1 categories — including the built-in ones. Edit a category
              to change its name, emoji, or preference hints. All vocabulary below Level 1 is auto-generated by AI.
            </p>
          </div>
        </div>

        {/* Category list */}
        {tree.length === 0 && (
          <p className="text-sm text-muted-foreground text-center py-8 bg-white rounded-xl border">
            No categories yet. Add one below.
          </p>
        )}

        <div className="space-y-3">
          {tree.map((category) => {
            const isGenerating = generatingId === category.id
            const isDeleting = deletingId === category.id
            const isEditing = editingId === category.id
            const hasContent = category.children.length > 0
            const leafCount = category.children.reduce((n, b) => n + b.children.length, 0)

            if (isEditing) {
              return (
                <div key={category.id} className="p-4 bg-white rounded-xl border shadow-sm space-y-3">
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={editEmoji}
                      onChange={(e) => setEditEmoji(e.target.value)}
                      placeholder="🎯"
                      className="w-14 text-center text-xl border rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-primary"
                      maxLength={8}
                      aria-label="Category emoji"
                    />
                    <input
                      type="text"
                      value={editName}
                      onChange={(e) => setEditName(e.target.value)}
                      placeholder="Category name"
                      className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                      aria-label="Category name"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-sm font-medium text-gray-700">
                      Preferences & hints <span className="text-gray-400 font-normal">(optional)</span>
                    </label>
                    <textarea
                      value={editDescription}
                      onChange={(e) => setEditDescription(e.target.value)}
                      placeholder="Describe what your child prefers in this category. E.g. 'Loves dosa, idli, and paapad. Not a fan of cold drinks.'"
                      className="w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                      rows={3}
                      aria-label="Category preferences and hints"
                    />
                    <p className="text-xs text-gray-400">
                      After changing the hints, use the regenerate button to refresh the vocabulary with the new preferences.
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" onClick={() => handleSaveEdit(category)} disabled={!editName.trim()}>
                      Save
                    </Button>
                    <Button variant="outline" size="sm" onClick={cancelEdit}>
                      Cancel
                    </Button>
                  </div>
                </div>
              )
            }

            return (
              <div
                key={category.id}
                className="flex items-start gap-3 p-4 bg-white rounded-xl border shadow-sm"
              >
                <span className="text-3xl w-10 text-center shrink-0 mt-0.5">{category.emoji}</span>
                <div className="flex-1 min-w-0">
                  <p className="font-semibold text-gray-800">{category.word}</p>
                  {category.description && (
                    <p className="text-xs text-gray-500 italic mt-0.5 line-clamp-2">{category.description}</p>
                  )}
                  <p className="text-xs text-gray-400 mt-1">
                    {isGenerating
                      ? "Generating vocabulary…"
                      : hasContent
                        ? `${category.children.length} sub-categories · ${leafCount} phrases`
                        : "No vocabulary yet — regenerate to create"}
                  </p>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  {isDeleting ? (
                    <>
                      <Button variant="destructive" size="sm" onClick={() => handleDelete(category.id)}>
                        Delete
                      </Button>
                      <Button variant="outline" size="sm" onClick={() => setDeletingId(null)}>
                        Cancel
                      </Button>
                    </>
                  ) : (
                    <>
                      <Button
                        variant="outline"
                        size="sm"
                        title="Edit name, emoji & hints"
                        onClick={() => startEdit(category)}
                        disabled={isBusy}
                      >
                        <Pencil className="w-4 h-4" />
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        title="Regenerate vocabulary"
                        onClick={() => handleRegenerate(category)}
                        disabled={isBusy}
                      >
                        {isGenerating ? (
                          <Loader2 className="w-4 h-4 animate-spin" />
                        ) : (
                          <RefreshCw className="w-4 h-4" />
                        )}
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        title="Delete category"
                        onClick={() => setDeletingId(category.id)}
                        disabled={isBusy}
                      >
                        <Trash2 className="w-4 h-4 text-red-500" />
                      </Button>
                    </>
                  )}
                </div>
              </div>
            )
          })}
        </div>

        {/* Error */}
        {error && (
          <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
            {error}
          </p>
        )}

        {/* Add new category */}
        <div className="bg-white rounded-xl border shadow-sm p-5 space-y-4">
          <p className="font-semibold text-gray-800">Add New Category</p>
          <div className="flex gap-2">
            <input
              type="text"
              value={newEmoji}
              onChange={(e) => setNewEmoji(e.target.value)}
              placeholder="🎯"
              className="w-14 text-center text-xl border rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-primary"
              maxLength={8}
              aria-label="Category emoji"
            />
            <input
              type="text"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              placeholder="Category name (e.g., Sports)"
              className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              onKeyDown={(e) => e.key === "Enter" && !isBusy && handleAdd()}
              aria-label="Category name"
            />
          </div>

          <div className="space-y-1">
            <label className="text-sm font-medium text-gray-700">
              Preferences & hints <span className="text-gray-400 font-normal">(optional)</span>
            </label>
            <textarea
              value={newDescription}
              onChange={(e) => setNewDescription(e.target.value)}
              placeholder="Describe what your child prefers in this category. E.g. 'Loves dinosaurs, superheroes, and building with LEGO. Dislikes loud toys.'"
              className="w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary resize-none"
              rows={3}
              aria-label="Category preferences and hints"
            />
            <p className="text-xs text-gray-400">
              If filled in, the AI will use these preferences to personalise the vocabulary for your child.
            </p>
          </div>

          <Button onClick={handleAdd} disabled={!newName.trim() || isBusy} className="w-full sm:w-auto">
            {isBusy ? (
              <Loader2 className="w-4 h-4 animate-spin mr-2" />
            ) : (
              <Plus className="w-4 h-4 mr-1" />
            )}
            Add Category
          </Button>
          <p className="text-xs text-gray-400">
            Adding a category automatically generates all sub-categories and phrases. This takes a few seconds.
          </p>
        </div>
      </div>
    </div>
  )
}
